### ISSUE TITLE
User is redirected back to original sync window

### ISSUE THREAD

**Issue by Mohith93** [Multiwoven/multiwoven#385] opened 2024-09-27 13:47 UTC
**Describe the bug**
User is redirected back to original sync window, when empty model in account

Environment : OSS, Staging, Production
Precondition : Model and sync should be empty.

**To Reproduce**

1. Login into application
2. Create successful source & destination
3. Go to sync and create a sync
4. Need to create model from creating sync, user will be redirected to model.
5. Add model is again redirecting user back to sync page.

Actual Behaviour: Once user hit on add model, user is redirected to sync page

**Expected behavior**
Add model should invoke model window instead of redirecting to sync.

https://github.com/user-attachments/assets/bde8b067-785b-422f-bf6e-423f0d803d93

**Comment by xyfer17** [comment] 2024-09-27 17:43
@Mohith93 I would like to take this issue, could you please assign this issue to me.

**Comment by xyfer17** [comment] 2024-10-04 13:02
@Mohith93, As you described, i tried to recreate it  but haven't found any issue on redirection, tested on my local machine by  taking  the latest pull of main branch, it's working fine. 

https://github.com/user-attachments/assets/3b68b2d8-9c8a-4a6b-9ab4-76543c22ab83

**Closed** 2024-10-07 15:27 UTC
Labels: bug, hacktoberfest

**Comment by sangkum** [comment] 2024-10-07 15:33
Verified & Found that the issue is not reproducible, Hence closing this ticket.
https://github.com/user-attachments/assets/82d89e8b-2d8a-440e-b94c-648d7d0e3bfb
